feature/dev-vicente (backend/controllers/routes): Finished the contro…
Sommelier-s/Backend pull request #17
Opened 2023-06-17 02:08 UTC by VicenteDeBlasi

- Modifique algunos controladores para
- Cree los controladores putLiquor & addCategoryToLiquor(Recomiendo revisar este primero)
- Termine las rutas de Liquor

2023-06-17 22:17 UTC, gonzam77 requested changes

2023-06-17 22:17 UTC, gonzam77 commented on src/server/settings/controllers/liquor/postLiquor.controller.js
> +        if (user.isAdmin === false) return res.status(401).json({ status: 401, error: "User is not an administrator" });
la propiedad isAdmin en realidad es is_Admin

2023-06-17 22:17 UTC, gonzam77 commented on src/server/settings/controllers/liquor/deleteLiquor.controller.js
> +        if (user.isAdmin === false) return res.status(401).json({ status: 401, error: "User is not an administrator" });
La propiedad isAdmin en realidad es is_Admin

2023-06-17 22:17 UTC, gonzam77 commented on src/server/settings/controllers/liquor/putLiquor.controller.js
> +        if (user.isAdmin === false) return res.status(401).json({ status: 401, error: "User is not an administrator" });
lo mismo que arriba

2023-06-17 22:28 UTC, gonzam77 requested changes, later dismissed

2023-06-17 22:28 UTC, gonzam77 commented on src/server/settings/controllers/liquor/addCategoryToLiquor.controller.js
> +        product.set({graduation: category});
product.setLiquor_category(category); en la linea 25 va así

2023-06-18 02:20 UTC, gonzam77 commented on src/server/settings/controllers/liquor/addCategoryToLiquor.controller.js
> +        product.set({graduation: category});
y lo que vamos a mandar es el id de la categoria no el nombre hay que revisar eso

2023-06-18 16:03 UTC, Fer-Mig-Agus approved these changes
Buen trabajo

2023-06-18 23:33 UTC, VicenteDeBlasi commented
ahi deberia estar

2023-06-19 00:04 UTC, closed without merging